{
 "title": "FortiADC",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "VirtualServer",
    "query": "show tag values from FortiADC_fadcVS with key = fadcVSName"
   }
  ]
 },
 "panels": [
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 1 },
   "content": "<img src=\"https://d3gpjj9d20n0p3.cloudfront.net/ngblog/uploads/images/Images/images%202/images%203/images%204/images%205/images%206/images%208/Hex%20blog/more%20hex/baidu/more%20baidu/cerber/Mamba/shamoon/Gartner/Breach%20blog/Logo.png\" height=\"100\"> <h2>FortiNET</>"
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 1 },
   "content": "# FortiADC\n* High-Performance Server Load Balancing and Application Delivery\n* Fast layer 4, layer 7, and SSL throughput\n* All app delivery and security features needed in single solution"
  },
  {
   "title": "Model",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "FortiADC",
     "select": [
      [
       { "params": [ "fadcSysModel" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Hostname",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "FortiADC",
     "select": [
      [
       { "params": [ "hostname" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "PeerStatus",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "FortiADC",
     "select": [
      [
       { "params": [ "fadcPeerStatus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Serial",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "FortiADC",
     "select": [
      [
       { "params": [ "fadcSysSerial" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 8 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "measurement": "FortiADC",
     "select": [
      [
       { "params": [ "fadcSysCpuUsage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 8 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "measurement": "FortiADC",
     "select": [
      [
       { "params": [ "fadcSysMemUsage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Load",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "FortiADC",
     "select": [
      [
       { "params": [ "fadcSysLoad" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Log Disk",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 8 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "measurement": "FortiADC",
     "select": [
      [
       { "params": [ "fadcSysLogDiskUsage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "FortiADC Log",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": { "size": 500 },
       "type": "raw_document"
      }
     ],
     "query": "gl2_source_input:5a34ee307d0962658371c65e AND NOT Target_Account:oxidized",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "Pool Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Virtual Server",
   "type": "vonage-status-panel",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 19 },
   "repeat": "VirtualServer",
   "targets": [
    {
     "aggregation": "Last",
     "alias": "Status",
     "crit": "Dead",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "measurement": "FortiADC_fadcVS",
     "select": [
      [
       { "params": [ "fadcVSHealth" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fadcVSName", "operator": "=~", "value": "/^$VirtualServer$/" }
     ],
     "units": "none",
     "valueHandler": "String Threshold",
     "warn": "Unhealthy"
    }
   ]
  },
  { "title": "Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Virtual Server Concurrent Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_fadcVSName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "fadcVSName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FortiADC_fadcVS",
     "select": [
      [
       { "params": [ "fadcVSConcurrent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "fadcVSName", "operator": "=~", "value": "/^$VirtualServer$/" }
     ]
    }
   ]
  },
  {
   "title": "Virtual Server New Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_fadcVSName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "fadcVSName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FortiADC_fadcVS",
     "select": [
      [
       { "params": [ "fadcVSNewConnections" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "fadcVSName", "operator": "=~", "value": "/^$VirtualServer$/" }
     ]
    }
   ]
  },
  {
   "title": "Virtual Server Troughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 23 },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "alias": "$tag_fadcVSName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "fadcVSName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FortiADC_fadcVS",
     "select": [
      [
       { "params": [ "fadcVSThroughputKbps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "fadcVSName", "operator": "=~", "value": "/^$VirtualServer$/" }
     ]
    }
   ]
  },
  {
   "title": "Interface Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "In:$tag_ifDescr",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ifDescr" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FortiADC_if",
     "select": [
      [
       { "params": [ "ifInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ]
    },
    {
     "alias": "Out:$tag_ifDescr",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ifDescr" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FortiADC_if",
     "select": [
      [
       { "params": [ "ifOutOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Interface Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "none", "label": "Errors" }
   ],
   "targets": [
    {
     "alias": "In:$tag_ifDescr",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ifDescr" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FortiADC_if",
     "select": [
      [
       { "params": [ "ifInErrors" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ]
    },
    {
     "alias": "Out:$tag_ifDescr",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ifDescr" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FortiADC_if",
     "select": [
      [
       { "params": [ "ifOutErrors" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "CPU",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FortiADC",
     "select": [
      [
       { "params": [ "fadcSysCpuUsage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "Mem",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FortiADC",
     "select": [
      [
       { "params": [ "fadcSysMemUsage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU Temperature",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "$tag_fadcCPUName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "fadcCPUName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FortiADC_fadcCPU",
     "select": [
      [
       { "params": [ "fadcCPUTemp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5" ], "type": "moving_average" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Device Temperature",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 43 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "$tag_fadcDeviceTempName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "fadcDeviceTempName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FortiADC_fadcDeviceTemp",
     "select": [
      [
       { "params": [ "fadcDeviceTempValue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5" ], "type": "moving_average" }
      ]
     ]
    }
   ]
  },
  {
   "title": "FAN",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 43 },
   "yaxes": [
    { "format": "none", "label": "rpm" }
   ],
   "targets": [
    {
     "alias": "$tag_fadcDeviceFanName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "fadcDeviceFanName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FortiADC_fadcDeviceFan",
     "select": [
      [
       { "params": [ "fadcDeviceFanSpeed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5" ], "type": "moving_average" }
      ]
     ]
    }
   ]
  }
 ]
}